function tableout = importTires(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   tireCoefficients = importTires('tireCoefficients.xlsx','Sheet1',2,4);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2020/02/05 15:49:46

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 4;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:Z%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:Z%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.rowNames = stringVectors(:,1);
tableout.a1 = data(:,1);
tableout.a2 = data(:,2);
tableout.a3 = data(:,3);
tableout.a4 = data(:,4);
tableout.a5 = data(:,5);
tableout.a6 = data(:,6);
tableout.a7 = data(:,7);
tableout.a8 = data(:,8);
tableout.a9 = data(:,9);
tableout.a10 = data(:,10);
tableout.a11 = data(:,11);
tableout.a12 = data(:,12);
tableout.a13 = data(:,13);
tableout.shxa = data(:,14);
tableout.bxa = data(:,15);
tableout.exa = data(:,16);
tableout.rcx1 = data(:,17);
tableout.rcx2 = data(:,18);
tableout.rcx3 = data(:,19);
tableout.rcx4 = data(:,20);
tableout.rcx5 = data(:,21);
tableout.rcx6 = data(:,22);
tableout.rcx7 = data(:,23);




