function VarName4 = importSpeed(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   VarName4 = IMPORTFILE1(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as
%   column vectors.
%
%   VarName4 = IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
%
%   VarName4 = IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the
%   specified worksheet for the specified row interval(s). Specify STARTROW
%   and ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   VarName4 = importSpeed('winstonProcessed.xlsx','Sheet1',1,952);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2019/11/15 13:54:09

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 952;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('D%d:D%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('D%d:D%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
VarName4 = data(:,1);

