function [Latitude, Longitude] = importRawTrack(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [LATITUDE, LONGITUDE] = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [LATITUDE, LONGITUDE] = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Latitude, Longitude] = importfile("C:\Users\Charles\Desktop\College Fall 2019\SD1\trackData\Log-20191020-134416 winston 8.19.20 - 0.45.949 - Interpolated.csv", [9, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Oct-2019 11:15:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Latitude", "Longitude", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16"];
opts.SelectedVariableNames = ["Latitude", "Longitude"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Latitude = tbl.Latitude;
Longitude = tbl.Longitude;
end